// Mocks generated by Mockito 5.3.2 from annotations
// in flutter_clean_architecture/test/features/auth/domain/usecases/sign_in_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_clean_architecture/core/either/either.dart' as _i2;
import 'package:flutter_clean_architecture/core/error/failure.dart' as _i5;
import 'package:flutter_clean_architecture/features/auth/domain/entities/sign_in/sign_in_request_entity.dart'
    as _i9;
import 'package:flutter_clean_architecture/features/auth/domain/entities/sign_in/sign_in_response_entity.dart'
    as _i8;
import 'package:flutter_clean_architecture/features/auth/domain/entities/sign_up/sign_up_request_entity.dart'
    as _i7;
import 'package:flutter_clean_architecture/features/auth/domain/entities/sign_up/sign_up_response_entity.dart'
    as _i6;
import 'package:flutter_clean_architecture/features/auth/domain/repository/auth_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.SignUpResponseEntity>> signUp(
          _i7.SignUpRequestEntity? requestEntity) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [requestEntity],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.SignUpResponseEntity>>.value(
                _FakeEither_0<_i5.Failure, _i6.SignUpResponseEntity>(
          this,
          Invocation.method(
            #signUp,
            [requestEntity],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.SignUpResponseEntity>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.SignInResponseEntity>> signIn(
          _i9.SignInRequestEntity? requestEntity) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [requestEntity],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i8.SignInResponseEntity>>.value(
                _FakeEither_0<_i5.Failure, _i8.SignInResponseEntity>(
          this,
          Invocation.method(
            #signIn,
            [requestEntity],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i8.SignInResponseEntity>>);
}
