// Mocks generated by Mockito 5.3.2 from annotations
// in flutter_clean_architecture/test/features/advices/presentation/bloc/category_list/category_list_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_clean_architecture/core/either/either.dart' as _i3;
import 'package:flutter_clean_architecture/core/error/failure.dart' as _i6;
import 'package:flutter_clean_architecture/features/advices/domain/entities/category_list_entity.dart'
    as _i7;
import 'package:flutter_clean_architecture/features/advices/domain/repository/advices_repository.dart'
    as _i2;
import 'package:flutter_clean_architecture/features/advices/domain/usecases/get_category_list.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAdvicesRepository_0 extends _i1.SmartFake
    implements _i2.AdvicesRepository {
  _FakeAdvicesRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetCategoryList].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCategoryList extends _i1.Mock implements _i4.GetCategoryList {
  MockGetCategoryList() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AdvicesRepository get advicesRepository => (super.noSuchMethod(
        Invocation.getter(#advicesRepository),
        returnValue: _FakeAdvicesRepository_0(
          this,
          Invocation.getter(#advicesRepository),
        ),
      ) as _i2.AdvicesRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.CategoryListEntity>> call(
          [_i4.Params? params]) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i7.CategoryListEntity>>.value(
                _FakeEither_1<_i6.Failure, _i7.CategoryListEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.CategoryListEntity>>);
}
